ls:
    ./**/{src,cypress}:
        .dir: kebab-case
        .ts: kebab-case
        .test.ts: kebab-case
        .tsx: kebab-case
        .test.tsx: kebab-case
        .d.ts: kebab-case
        .module.css: kebab-case

    ./**/node_modules:
        .dir: regex:.*

ignore:
    - node_modules
    - .d2
    - build
