ls:
    '{cypress,scripts,src,types}':
        .dir: kebab-case | regex:__tests__ | regex:__snapshots__ | regex:__fixtures__
        .ts: kebab-case
        .spec.ts: kebab-case
        .tsx: kebab-case
        .spec.tsx: kebab-case
        .d.ts: kebab-case
        .cy.ts: kebab-case
        .cy.tsx: kebab-case
        .module.css: kebab-case
        .sh: kebab-case
        .json: kebab-case

ignore:
    - src/types/dhis2-openapi-schemas
