sonar.host.url=https://sonarcloud.io
sonar.organization=dhis2
sonar.projectKey=dhis2_event-visualizer-app
sonar.sources=src
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=**/node_modules/**,**/build/**,**/.d2/**
