import type { ValueType } from '@types'

export const NUMERIC_VALUE_TYPES: ValueType[] = [
    'NUMBER',
    'UNIT_INTERVAL',
    'PERCENTAGE',
    'INTEGER',
    'INTEGER_POSITIVE',
    'INTEGER_NEGATIVE',
    'INTEGER_ZERO_OR_POSITIVE',
] as const

export const VALUE_TYPES: ValueType[] = [
    'AGE',
    'BOOLEAN',
    'COORDINATE',
    'DATE',
    'DATETIME',
    'EMAIL',
    'FILE_RESOURCE',
    'GEOJSON',
    'IMAGE',
    'INTEGER_NEGATIVE',
    'INTEGER_POSITIVE',
    'INTEGER_ZERO_OR_POSITIVE',
    'INTEGER',
    'LETTER',
    'LONG_TEXT',
    'MULTI_TEXT',
    'NUMBER',
    'ORGANISATION_UNIT',
    'PERCENTAGE',
    'PHONE_NUMBER',
    'REFERENCE',
    'TEXT',
    'TIME',
    'TRACKER_ASSOCIATE',
    'TRUE_ONLY',
    'UNIT_INTERVAL',
    'URL',
    'USERNAME',
] as const
