/**
 * Regenerates the line-list fixtures from the DHIS2 instance in
 * cypress.env.json, exercising the real production code path: the saved
 * visualization is loaded and normalized the way the app does it, and the
 * analytics + legendSets responses are captured verbatim from the requests
 * the real useLineListAnalyticsData hook makes. Every fixture file is fully
 * generated by this script.
 *
 * Skipped unless explicitly requested:
 *
 *   RECAPTURE_LINE_LIST_FIXTURES=1 pnpm exec vitest run src/test-utils/recapture-line-list-fixtures.spec.tsx
 *
 * Run `pnpm format` afterwards to normalize the written JSON.
 *
 * Fixtures that have no saved counterpart on the instance are defined here
 * as variations: a delta applied to a fetched base visualization, or a
 * visualization built from fetched program metadata.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { getVisualizationQueryFields } from '@api/event-visualizations-api'
import {
    useLineListAnalyticsData,
    type LineListAnalyticsData,
} from '@components/plugin-wrapper/hooks/use-line-list-analytics-data'
import { Provider } from '@dhis2/app-runtime'
import { transformVisualizationForAnalyticsRequest } from '@modules/analytics-request'
import { getProgramFields } from '@modules/query'
import { normalizeApiSavedVisualization } from '@modules/visualization/state'
import { renderHook, waitFor } from '@testing-library/react'
import type {
    ApiSavedVisualization,
    CurrentVisualization,
    SavedVisualization,
} from '@types'
import type { FC, ReactNode } from 'react'
import { ErrorBoundary } from 'react-error-boundary'
import { describe, it, vi, expect } from 'vitest'
import { createLineListFixtureMetadataStore } from './line-list-fixtures'

const mockUseMetadataStore = vi.hoisted(() => vi.fn())
vi.mock('@components/app-wrapper/metadata-provider/metadata-provider', () => ({
    useMetadataStore: mockUseMetadataStore,
}))

const FIXTURES_DIR = resolve(__dirname, '../components/line-list/__fixtures__')

type ApiVisualizationSource =
    /* a saved visualization on the instance */
    | { id: string }
    /* a delta applied to a saved visualization */
    | { baseId: string; vary: (base: ApiSavedVisualization) => unknown }
    /* built from scratch (fetchProgram provides server program metadata) */
    | {
          build: (
              fetchProgram: (id: string) => Promise<unknown>
          ) => Promise<unknown>
      }

type FixtureDefinition = {
    name: string
    source: ApiVisualizationSource
    /* Store state the app only builds in the editor (e.g. the per-data-item
     * legend set IDs it fetches), which loading a visualization does not
     * seed. Written into the fixture for the component tests. */
    metadata?: Record<string, unknown>
}

/* "Inpatient: Cases under 5 years female this year (case)" with numeric and
 * program-indicator columns added (some deliberately duplicated) and a
 * by-data-item legend, so legend resolution and coloring can be tested. */
const programIndicatorColumn = (id: string) => ({
    dimension: id,
    dimensionType: 'PROGRAM_INDICATOR',
    items: [],
})

const withAdditionalColumnsAndLegends = (
    base: ApiSavedVisualization
): unknown => {
    const baseColumns = base.columns as Array<{ dimension: string }>
    const baseColumn = (id: string) =>
        baseColumns.find((column) => column.dimension === id)!
    return {
        ...base,
        name: `${base.name} additional columns and legends`,
        legend: {
            set: { id: 'OrkEzxZEH4X' },
            strategy: 'BY_DATA_ITEM',
            style: 'FILL',
            showKey: true,
        },
        columns: [
            baseColumns[0], // pe THIS_YEAR
            {
                dimension: 'vV9UWAZohSf', // Weight in kg
                dimensionType: 'PROGRAM_DATA_ELEMENT',
                valueType: 'INTEGER_POSITIVE',
                items: [],
            },
            ...baseColumns.slice(1),
            programIndicatorColumn('x7PaHGvgWY2'), // BMI
            programIndicatorColumn('hlPt8H4bUOQ'), // BMI female under 5 y
            programIndicatorColumn('b8hd33dWjR6'), // Inpatient bed days
            programIndicatorColumn('vDdRoZYybP2'), // Inpatient cases under 5 y
            programIndicatorColumn('gWxh7DiRmG7'), // Average height of girls at 5
            // duplicates of data elements already in the base
            baseColumn('K6uUAvq500H'),
            baseColumn('eMyVanycQSC'),
            programIndicatorColumn('ReQEl5V3z6p'), // Average weight of women
        ],
    }
}

/* A line list without any time dimension, for the NoTimeDimensionWarning:
 * user org unit plus a boolean data element on the ANC visit program. */
const buildNoTimeDimensionVisualization = async (
    fetchProgram: (id: string) => Promise<unknown>
): Promise<unknown> => {
    const program = (await fetchProgram('lxAQ7Zs9VYR')) as {
        programStages: unknown[]
    }
    return {
        name: 'No time dimension',
        type: 'LINE_LIST',
        outputType: 'EVENT',
        program,
        programStage: program.programStages[0],
        metaData: {},
        columns: [
            { dimension: 'ou', items: [{ id: 'USER_ORGUNIT' }] },
            { dimension: 'sWoqcoByYmD', items: [] }, // WHOMCH Smoking (boolean)
        ],
    }
}

const FIXTURES: FixtureDefinition[] = [
    { name: 'e2e-enrollment', source: { id: 'AFjkDs7acBh' } },
    {
        name: 'inpatient-cases-under-5-years-female-this-year-additional-columns-and-legends',
        source: {
            baseId: 'pLJAnM1rHex',
            vary: withAdditionalColumnsAndLegends,
        },
        metadata: {
            'Zj7UnCAulEk.vV9UWAZohSf': {
                id: 'Zj7UnCAulEk.vV9UWAZohSf',
                dimensionId: 'vV9UWAZohSf',
                name: 'Weight in kg',
                dimensionType: 'DATA_ELEMENT',
                valueType: 'INTEGER_POSITIVE',
                programStageId: 'Zj7UnCAulEk',
                legendSetId: 'OrkEzxZEH4X',
            },
            'Zj7UnCAulEk.qrur9Dvnyt5': {
                id: 'Zj7UnCAulEk.qrur9Dvnyt5',
                dimensionId: 'qrur9Dvnyt5',
                name: 'Age in years',
                dimensionType: 'DATA_ELEMENT',
                valueType: 'INTEGER',
                programStageId: 'Zj7UnCAulEk',
                legendSetId: 'Yf6UHoPkdS6',
            },
        },
    },
    {
        name: 'inpatient-visit-overview-this-year-bombali',
        source: { id: 'kb9Uml5FEEz' },
    },
    {
        name: 'no-time-dimension',
        source: { build: buildNoTimeDimensionVisualization },
    },
]

describe.runIf(process.env.RECAPTURE_LINE_LIST_FIXTURES)(
    'recapture line-list fixtures',
    () => {
        const cypressEnv = JSON.parse(
            readFileSync(resolve(__dirname, '../../cypress.env.json'), 'utf8')
        )
        const authHeader =
            'Basic ' +
            Buffer.from(
                `${cypressEnv.dhis2Username}:${cypressEnv.dhis2Password}`
            ).toString('base64')

        /* The data engine authenticates with cookies in the browser; here
         * every request gets basic auth injected, and JSON responses are
         * recorded so they can be saved verbatim. */
        const recorded: Array<{ url: string; body: unknown }> = []
        const realFetch = globalThis.fetch
        globalThis.fetch = (async (
            input: RequestInfo | URL,
            init?: RequestInit
        ) => {
            const url = String(input)
            const response = await realFetch(url, {
                ...init,
                credentials: undefined,
                headers: {
                    ...(init?.headers as object),
                    Authorization: authHeader,
                },
            } as RequestInit)
            try {
                recorded.push({ url, body: await response.clone().json() })
            } catch {
                // non-JSON response, ignore
            }
            return response
        }) as typeof fetch

        const fetchJson = async (path: string): Promise<unknown> => {
            const response = await globalThis.fetch(
                `${cypressEnv.dhis2BaseUrl}${path}`
            )
            if (!response.ok) {
                throw new Error(`GET ${path} failed: ${response.status}`)
            }
            return await response.json()
        }

        const fetchApiVisualization = (id: string) =>
            fetchJson(
                `/api/eventVisualizations/${id}?fields=${encodeURIComponent(
                    getVisualizationQueryFields('displayName').join(',')
                )}`
            )

        const fetchProgram = (id: string) =>
            fetchJson(
                `/api/programs/${id}?fields=${encodeURIComponent(
                    getProgramFields('displayName')
                )}`
            )

        const resolveVisualization = async (
            source: ApiVisualizationSource
        ): Promise<SavedVisualization> => {
            if ('id' in source) {
                return normalizeApiSavedVisualization(
                    (await fetchApiVisualization(
                        source.id
                    )) as ApiSavedVisualization
                )
            }
            if ('baseId' in source) {
                return normalizeApiSavedVisualization(
                    source.vary(
                        (await fetchApiVisualization(
                            source.baseId
                        )) as ApiSavedVisualization
                    ) as ApiSavedVisualization
                )
            }
            return normalizeApiSavedVisualization(
                (await source.build(fetchProgram)) as ApiSavedVisualization
            )
        }

        const Wrapper: FC<{ children: ReactNode }> = ({ children }) => (
            <Provider
                config={{
                    baseUrl: cypressEnv.dhis2BaseUrl,
                    apiVersion: Number(cypressEnv.dhis2InstanceVersion),
                }}
                userInfo={undefined}
                plugin={false}
                parentAlertsAdd={undefined}
                showAlertsInPlugin={false}
            >
                <ErrorBoundary fallback={<div>error</div>}>
                    {children}
                </ErrorBoundary>
            </Provider>
        )

        it.each(FIXTURES)(
            'recaptures $name',
            async ({ name, source, metadata }) => {
                const visualization = await resolveVisualization(source)
                mockUseMetadataStore.mockReturnValue(
                    createLineListFixtureMetadataStore([
                        { visualization, metadata },
                    ])
                )

                recorded.length = 0
                const { result, unmount } = renderHook(
                    () => useLineListAnalyticsData(),
                    { wrapper: Wrapper }
                )
                const [fetchAnalyticsData] = result.current
                await fetchAnalyticsData({
                    visualization: transformVisualizationForAnalyticsRequest(
                        visualization as CurrentVisualization
                    ),
                    displayProperty: 'name',
                    onResponseReceived: () => undefined,
                })
                await waitFor(() => {
                    expect(result.current[1].data).not.toBeNull()
                })
                const analyticsData = result.current[1]
                    .data as LineListAnalyticsData
                unmount()

                const analytics = recorded.find((request) =>
                    request.url.includes('/analytics/')
                )
                expect(
                    analytics,
                    `analytics response for ${name}`
                ).toBeDefined()

                writeFileSync(
                    resolve(FIXTURES_DIR, `${name}.json`),
                    JSON.stringify(
                        {
                            visualization,
                            ...(metadata ? { metadata } : {}),
                            response: analytics!.body,
                            legendSets: analyticsData.legendSets,
                        },
                        null,
                        4
                    ) + '\n'
                )
            },
            60000
        )
    }
)
