#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Vitest tests"
pnpm test

echo "Running Cypress Component Tests"
# https://github.com/cypress-io/cypress/issues/29723#issuecomment-2182931609
unset ELECTRON_RUN_AS_NODE
pnpm cy:comp:run
