name: PR Task List Checker
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

# cancel old edit events being processed
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    validate-checklists:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Validate Checklists
              uses: roryq/checkmate@master
