name: 'Enable auto-merge for Dependabot PRs'

on:
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    pull-requests: write
    contents: write

jobs:
    enable-automerge:
        runs-on: ubuntu-latest

        # Only run on Dependabot PRs
        if: github.event.pull_request.user.login == 'dependabot[bot]'

        steps:
            - name: Enable auto-merge (squash)
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                  pull-request-number: ${{ github.event.pull_request.number }}
                  merge-method: squash
