name: 'deploy to AWX EVER instance'

on:
    schedule:
        - cron: '0 5 * * *' # Runs every day at 5:00 AM UTC
    push:
        branches:
            - master
        tags:
            - '*'
    workflow_dispatch: # Allows manual triggering of the workflow

env:
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    CI: true

jobs:
    deploy-to-awx-ever-instance:
        if: |
            ${{ !github.event.push.repository.fork }} &&
            ${{ github.ref == 'refs/heads/master' ||  startsWith(github.ref, 'refs/tags/') }}

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install
              run: yarn install --frozen-lockfile --ignore-scripts

            - name: Build
              run: yarn d2-app-scripts build

            - name: Deploy build to AWX EVER instance
              run: yarn d2-app-scripts deploy https://test.e2e.dhis2.org/anly-ever --username=admin --password=district
