name: 'This workflow creates bill of material and uploads it to Dependency-Track each night'

on:
    schedule:
        - cron: '0 0 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    create-bom:
        uses: dhis2/workflows-platform/.github/workflows/generate-and-upload-bom.yml@v1
        with:
            node-version: lts/*
            project_id: '7a585a7b-1604-4d50-b6f4-9429e290362a'
        secrets: inherit
